spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/skitrainerdb
    username: skiuser
    password: skipassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update


jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

google:
  oauth:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: http://localhost:8080/api/oauth2/callback