spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/skitrainerdb
    username: skiuser
    password: skipassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000